background {
    monitor =
    path = ~/.config/omarchy/themes/omarchy-silver-phantom/unlock.png
    blur_passes = 2
    blur_size = 5
}

input-field {
    monitor =
    size = 280, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true
    outer_color = rgba(216, 219, 230, 0.8)
    inner_color = rgba(9, 10, 15, 0.9)
    font_color = rgb(230, 232, 242)
    fade_on_empty = false
    placeholder_text = <span foreground="##606575">Silver Phantom</span>
    hide_input = false
    check_color = rgba(216, 219, 230, 0.8)
    fail_color = rgba(176, 180, 195, 0.8)
    position = 0, -80
    halign = center
    valign = center
}
