# Omarchy Silver Phantom - Hyprland Config
# Dual-Tone Silver & Pitch Obsidian Black Stance

general {
    col.active_border = rgba(e6e8f2cc) rgba(5d627466) 45deg
    col.inactive_border = rgba(14161f88)
    border_size = 2
    gaps_in = 6
    gaps_out = 12
}

decoration {
    rounding = 8
    
    shadow {
        enabled = true
        range = 16
        render_power = 4
        color = rgba(000000bb)
        color_inactive = rgba(00000088)
    }
}
